### ISSUE TITLE
Can pineapple.js be use in production for long term !?

### ISSUE THREAD

**Issue by florindumitru** [snapshot-labs/pineapple.js#24]
Can pineapple.js be used in production(with https://pineapple.fyi), there is any risk involved in "unpinning" the json files pinned with this lib in the future ?

Thanks

**Comment by bonustrack** [comment]
@florindumitru I don't recommend to do this atm, we will do some core change that will most likely break your code, we plan to introduce API keys and add a fee to avoid abuse.
